In [1]:
import numpy as np

In [3]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [8]:
# print(a*b) we cannot do thid
#but we can use mutual multiplication
print(np.matmul(a,b))

[[6. 6.]
 [6. 6.]]


In [9]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# create a random matrix
size = 4

random_matrix = np.random.rand(size, size)
print(random_matrix)

[[0.34597403 0.62512999 0.06659975 0.89364002]
 [0.24309127 0.85392583 0.79669874 0.45681864]
 [0.82240311 0.14746191 0.59603347 0.69898398]
 [0.68568425 0.1142566  0.03833941 0.9677291 ]]


In [30]:
#random int matrix
random_int_matrix = np.random.randint(1, 100, size=(size, size))
print(random_int_matrix)

[[71 98 34 29]
 [52 28 15  5]
 [93 93 31 72]
 [12 66 60 85]]


In [31]:
#for finging the determinent
print(np.linalg.det(random_int_matrix))

7372220.999999998


In [32]:
#Calculating Eigenvalues and Eigenvectors

print(np.linalg.eig(random_int_matrix))

EigResult(eigenvalues=array([194.33519048+0.j       ,  67.1775023 +0.j       ,
       -23.25634639+4.8835628j, -23.25634639-4.8835628j]), eigenvectors=array([[ 0.48580421+0.j        , -0.34213775+0.j        ,
        -0.0732326 +0.18358214j, -0.0732326 -0.18358214j],
       [ 0.22643528+0.j        , -0.29246326+0.j        ,
        -0.11837397-0.206034j  , -0.11837397+0.206034j  ],
       [ 0.64542371+0.j        ,  0.12760827+0.j        ,
         0.85862387+0.j        ,  0.85862387-0.j        ],
       [ 0.54419626+0.j        ,  0.8838117 +0.j        ,
        -0.39953309+0.08723843j, -0.39953309-0.08723843j]]))
