In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [5]:
after1 = before.reshape(2,2,2)
print(after1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#vartically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [14]:
#horizontal stack
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

print(np.hstack([v1,v2]))
print(np.hstack([v1,v1,v2,v2]))

[1 2 3 4 5 6 7 8]
[1 2 3 4 1 2 3 4 5 6 7 8 5 6 7 8]
