In [17]:
import numpy as np


In [18]:
a = np.random.randint(1, 100, size=(3,3))
print(a)

[[ 5 59 58]
 [64  4 22]
 [14  8 29]]


In [19]:
print(np.mean(a))

29.22222222222222


In [20]:
print(np.min(a))

4


In [21]:
print(np.max(a))

64


In [23]:
print(np.sum(a))

263


In [24]:
print(np.sum(a, axis=0))


[ 83  71 109]
