In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
a.shape

(2, 7)

In [13]:
#row specific element [row, column]
print("use positive element ----> ",a[1,5])
print("use negative element ----> ",a[1,-2])
print("all item of a row ----> ",a[0, :])

use positive element ---->  13
use negative element ---->  13
all item of a row ---->  [1 2 3 4 5 6 7]


In [14]:
#get a specific column
print(a[:, 2]) # : ----> mean all the element

[ 3 10]


In [15]:
#getting more fancy [startIndex : endIndex : stpesize]
print(a[0, 1:6:2])

[2 4 6]


In [16]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
a[:,2] = 99
print(a)

[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 20 14]]


In [29]:
a[0,:] = [54, 55, 56, 58, 59, 60, 61]
print(a)

[[54 55 56 58 59 60 61]
 [ 8  9 55 11 12 20 14]]


In [31]:
a[:,2] = [77,77]
print(a)

[[54 55 77 58 59 60 61]
 [ 8  9 77 11 12 20 14]]


In [33]:
#3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
#get specific element (get outside in
print(b[0,1,1])

4


In [35]:
print(b[:,1,:])

[[3 4]
 [7 8]]


In [42]:
#replace
b[:,1,:] = [[99,99],[98,98]]
print(b)

[[[99 99]
  [99 99]]

 [[98 98]
  [98 98]]]
