Initializing Different Types of Arrays

In [3]:
import numpy as np

In [8]:
#all zeros matrix(Row column)
print(np.zeros((2,2)))
print("===========================")
print(np.zeros((2,4)))
print("===========================")
print(np.zeros((2,3)))


[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#all ones matrix(Row column)
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [10]:
#matrix shape with value
print(np.full((2,2), 99))

[[99 99]
 [99 99]]


In [11]:
#all other number (full like)


In [17]:
#random decimal number
print(np.random.rand(4,2))
print("==================")
print(np.random.randn(4,2,3))


[[0.34744339 0.25124619]
 [0.73448755 0.40269427]
 [0.34439874 0.16458831]
 [0.85077516 0.93984384]]
[[[ 1.01923859  0.40670211 -0.58950653]
  [-1.26438077  2.209555   -0.67815334]]

 [[-0.56296003 -0.48431189 -0.10991857]
  [-0.9695478  -1.03312293 -0.48901657]]

 [[ 1.1956234   0.36185538 -0.74895894]
  [-0.76055743 -0.85876761  0.61152426]]

 [[-1.15154593 -1.25494684 -1.03694227]
  [ 1.13023032  2.16243747  1.46063279]]]


In [19]:
#random integer value
print(np.random.randint(4,7, size=(3,3))) # 4 is lower bound and 7 is upper bound here

[[5 6 6]
 [6 6 5]
 [6 6 5]]


In [23]:
#identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#repeat array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [25]:
#repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
r2 = np.repeat(arr,3, axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]
