In [18]:
import numpy as np

The Basics

In [19]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [20]:
b = np.array([[1,2,3],[4,5,6]]) #2d array
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
#get dimension
b.ndim

2

In [22]:
#get shape
a.shape

(6,)

In [23]:
#get shape
b.shape

(2, 3)

In [24]:
#get type
a.dtype

dtype('int64')

In [25]:
#get type
b.dtype

dtype('int64')

In [26]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="int16")
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
c.dtype

dtype('int16')

In [28]:
#get size
a.itemsize

8

In [29]:
c.itemsize

2

In [30]:
a.size

6

In [31]:
c.size

9

In [32]:
#get total size
a.nbytes

48

In [33]:
c.nbytes

18