In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
a.shape

(2, 7)

In [12]:
#row specific element [row, column]
print("use positive element ----> ",a[1,5])
print("use negative element ----> ",a[1,-2])
print("all item of a row ----> ",a[0, :])

use positive element ---->  13
use negative element ---->  13
[1 2 3 4 5 6 7]
